server.port=9093

spring.application.name=pesatone-api

spring.datasource.url= jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_SCHEMA:pesatone}
spring.datasource.username= ${DATABASE_USERNAME:pesatone}
spring.datasource.password= ${DATABASE_PASSWORD:p@ssw0rd}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql = false
spring.jpa.hibernate.naming.physical-strategy=com.pesatone.api.configuration.PhysicalNamingStrategyImpl
spring.jpa.hibernate.ddl-auto=update


application.jwtKey= ${PESATONE_JWT_SECRET_KEY:***REMOVED***}
application.jwtExpiry= ${PESATONE_JWT_EXPIRY_SECONDS:3600}
application.otpExpiry= ${OTP_EXPIRY_SECONDS:600}

application.passwordResetUrl= ${PESATONE_PASSWORD_RESET_URL:http://localhost/forgot-password/new/}
springdoc.swagger-ui.path=/api-doc.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

application.admin.email= ${PESATONE_ADMIN_EMAIL:phelixdusengimana@gmail.com}
application.admin.password= ${PESATONE_ADMIN_PASSWORD:***REMOVED***}

application.cloudinary.url= ${CLOUDINARY_URL:cloudinary://***REMOVED***:***REMOVED***@***REMOVED***}
application.cloudinary.name= ${CLOUDINARY_NAME:***REMOVED***}
application.cloudinary.api-key= ${CLOUDINARY_API_KEY:***REMOVED***}
application.cloudinary.api-secret= ${CLOUDINARY_API_SECRET:***REMOVED***}

application.payment.transactionFeePercentage= ${TRANSACTION_FEE_PERCENTAGE:10}
application.payment.flwVerifyHash= ${FLW_VERIFY_HASH:***REMOVED***}
application.payment.flwSecretKey= ${FLW_SECRET_KEY:***REMOVED***}
application.payment.flwTransactionDetailUrl= ${FLW_TRANSACTION_DETAIL_URL:https://api.flutterwave.com/v3/transactions/verify_by_reference}
application.payment.flwTransferUrl= ${FLW_TRANSFER_DETAIL_URL:https://api.flutterwave.com/v3/transfers}

application.mailjet.public-key= ${MAILJET_PUBLIC_KEY:***REMOVED***}
application.mailjet.secret-key= ${MAILJET_SECRET_KEY:***REMOVED***}

application.mail.sender= ${MAIL_SENDER:noreply@pesatone.com}

webclient.connect-timeout= ${WEBCLIENT_CONNECT_TIMEOUT:1000}
webclient.read-timeout= ${WEBCLIENT_READ_TIMEOUT:5000}

logging.level.com.zaxxer.hikari= ${HIKARI_LOG_LEVEL:WARN}