server.port=9093
server.compression.enabled=true
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.max-connections=8192
server.tomcat.accept-count=100
server.tomcat.connection-timeout=2000

spring.reactor.netty.connection.provider.pool.max-connections=10000
spring.reactor.netty.connection.provider.pool.acquire-timeout=5000


spring.application.name=pesatone-api

spring.datasource.url= jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}
spring.datasource.username= ${DATABASE_USERNAME}
spring.datasource.password= ${DATABASE_PASSWORD}

spring.jpa.show-sql = false
spring.jpa.hibernate.naming.physical-strategy=com.pesatone.api.configuration.PhysicalNamingStrategyImpl
spring.jpa.hibernate.ddl-auto=update


application.jwtKey= ${PESATONE_JWT_SECRET_KEY}
application.jwtExpiry= ${PESATONE_JWT_EXPIRY_SECONDS}
application.otpExpiry= ${OTP_EXPIRY_SECONDS}
application.statusNotificationDuration= ${STATUS_NOTIFICATION_DURATION}
application.statusNotificationEventKey= ${STATUS_NOTIFICATION_KEY}

application.passwordResetUrl= ${PESATONE_PASSWORD_RESET_URL}
springdoc.swagger-ui.path=/api-doc.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

application.admin.email= ${PESATONE_ADMIN_EMAIL}
application.admin.password= ${PESATONE_ADMIN_PASSWORD}

application.cloudinary.url= ${CLOUDINARY_URL}
application.cloudinary.name= ${CLOUDINARY_NAME}
application.cloudinary.api-key= ${CLOUDINARY_API_KEY}
application.cloudinary.api-secret= ${CLOUDINARY_API_SECRET}

application.payment.transactionFeePercentage= ${TRANSACTION_FEE_PERCENTAGE}
application.payment.flwVerifyHash= ${FLW_VERIFY_HASH}
application.payment.flwSecretKey= ${FLW_SECRET_KEY}
application.payment.flwTransactionDetailUrl= ${FLW_TRANSACTION_DETAIL_URL}
application.payment.flwTransferUrl= ${FLW_TRANSFER_DETAIL_URL}
application.payment.fdiAccountId= ${FDI_ACCOUNT_ID}
application.payment.fdiAppId= ${FDI_APP_ID}
application.payment.fdiSecret= ${FDI_SECRET}
application.payment.fdiPayoutUrl= ${FDI_PAYOUT_URL}
application.payment.fdiPaymentUrl= ${FDI_PAYMENT_URL}
application.payment.fdiTransactionDetailUrl= ${FDI_TRANSACTION_DETAIL_URL}
application.payment.fdiAuthUrl= ${FDI_AUTH_URL}
application.payment.fdiPaymentCallbackUrl= ${FDI_PAYMENT_CALLBACK_URL}
application.payment.fdiPayoutCallbackUrl= ${FDI_PAYOUT_CALLBACK_URL}
application.payment.poketMoneyBaseUrl= ${POKET_MONEY_BASE_URL}
application.payment.poketMoneyM2mApiKey= ${POKET_MONEY_M2M_API_KEY}
application.payment.poketMoneyCallbackUrlPayment= ${POKET_MONEY_CALLBACK_URL_PAYMENT}
application.payment.poketMoneyCallbackUrlPayout= ${POKET_MONEY_CALLBACK_URL_PAYOUT}

application.mailjet.public-key= ${MAILJET_PUBLIC_KEY}
application.mailjet.secret-key= ${MAILJET_SECRET_KEY}

application.resend.api-key= ${RESEND_API_KEY}

application.mail.sender= ${MAIL_SENDER}
application.mail.brand-name= ${MAIL_BRAND_NAME}

webclient.connect-timeout= ${WEBCLIENT_CONNECT_TIMEOUT}
webclient.read-timeout= ${WEBCLIENT_READ_TIMEOUT}

logging.level.com.zaxxer.hikari= ${HIKARI_LOG_LEVEL}

# spring.cache.jcache.config=classpath:ehcache.xml
spring.cache.cache-names=paymentTransaction,creator,creatorSearch
spring.cache.type=hazelcast
logging.level.com.hazelcast.map.impl: WARN
logging.level.com.hazelcast.internal.diagnostics.HealthMonitor=OFF

application.ratelimitMaxRequest= ${RATE_LIMIT_MAX_REQUESTS}
