server.port=9093

spring.application.name=pesatone-api

spring.datasource.url= ${PESATONE_DB_URL:jdbc:postgresql://127.0.0.1:5432/pesatone}
spring.datasource.username= ${PESATONE_DB_USER:pesatone}
spring.datasource.password= ${PESATONE_PASSWORD:p@ssw0rd}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.naming.physical-strategy=com.pesatone.api.configuration.PhysicalNamingStrategyImpl
spring.jpa.hibernate.ddl-auto=update
